<?php
/////// CB's piwigo-twitter CONFIGURATION

/* Fill this stuff out before you try running any of the other scripts.
 * otherwise you'll get all kinds of errors
 * The oauth token and oauth secret are generated when you run the
 * connect.php script, so make sure to come back here and add them
 */

//// PIWIGO SETUP
// Your Piwigo URL (i.e. http://yourpiwigo.com)
$piwigourl = "http://YOUR_PIWIGO_URL";

// Log file location (absolute path if setting up as a cron job)
$logfile = "/PATH/TO/YOUR/LOG/FILE.txt";

// Category (album) ID
$category_id = "YOUR_ALBUM_ID";		// i.e. 705

//// TUMBLR SETUP
// Your blog's URL
$blogname = "someblog.tumblr.com";

// The URL to the callback.php file (i.e. http://yourpiwigo.com/piwigo/callback.php)
$yourcallbackurl = "http://YOUR_PIWIGO/callback.php";

// OAuth info
// to get these - register an app at http://www.tumblr.com/oauth/apps
$yourconsumerkey = "YOUR_CONSUMER_KEY";
$yourconsumersecret = "YOUR_CONSUMER_SECRET";

// these two are generated by running connect.php
$youroauthtoken = "YOUR_OAUTH_TOKEN";
$youroauthsecret = "YOUR_OAUTH_SECRET";

// EXTRA
$yourcellemail = "YOUR_PHONE_SMS_EMAIL_ADDRESS";	// i.e. 5552345555@txt.att.net
$youremail = "YOUR_EMAIL_ADDRESS";					// i.e. yourname@email.com

?>
